#!/usr/bin/env python3
"""Emit db/seed.sql from scripts/seed_levels.py + scripts/seed_phrases.py (edit those, then run this)."""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(_ROOT))

from seed_levels import LEVEL_CODE_TO_ID, LEVEL_ROWS, LESSON_META  # noqa: E402
from seed_phrases import PHRASES  # noqa: E402


def esc(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "db" / "seed.sql"
    lines: list[str] = []
    lines.append(
        """-- Vocalia curriculum seed (European Portuguese — Portugal)
-- Generated by scripts/build_seed_sql.py from scripts/seed_levels.py + scripts/seed_phrases.py
--
-- Edit the Python source files for content changes, then run:
--   python3 scripts/build_seed_sql.py
--
-- Disclaimer: starter educational phrases for adults relocating from the US — friendly practice,
-- not certified linguistic instruction, legal advice, or medical advice.
-- Run after schema.sql. Safe to re-run: deletes curriculum rows only.

begin;

delete from public.phrases;
delete from public.lessons;
delete from public.levels;

"""
    )

    lvl_vals = ",\n".join(
        f"  ({esc(r[0])}, {esc(r[1])}, {esc(r[2])}, {esc(r[3])}, {r[4]}, {r[5]})"
        for r in LEVEL_ROWS
    )
    lines.append("insert into public.levels (id, code, title, description, sort_order, lesson_count) values\n")
    lines.append(lvl_vals)
    lines.append(";\n\n")

    order = [("A1", i) for i in range(1, 6)] + [("A2", i) for i in range(1, 6)] + [("B1", i) for i in range(1, 6)] + [("B2", i) for i in range(1, 6)]

    lesson_lines: list[str] = []
    for key in order:
        lid, title, desc = LESSON_META[key]
        level_id = LEVEL_CODE_TO_ID[key[0]]
        so = key[1]
        lesson_lines.append(
            f"  ({esc(lid)}, {esc(level_id)}, {esc(title)}, {esc(desc)}, {so})"
        )
    lines.append("insert into public.lessons (id, level_id, title, description, sort_order) values\n")
    lines.append(",\n".join(lesson_lines))
    lines.append(";\n\n")

    for key in order:
        lid = LESSON_META[key][0]
        rows = PHRASES.get(key)
        if not rows or len(rows) != 10:
            raise SystemExit(f"Expected 10 phrases for {key}, got {len(rows or [])}")
        ph_lines: list[str] = []
        for i, (pt, en, ph, sy, no, mi) in enumerate(rows, start=1):
            sy_sql = "NULL" if sy is None else esc(sy)
            no_sql = "NULL" if no is None else esc(no)
            mi_sql = "NULL" if mi is None else esc(mi)
            ph_lines.append(
                f"  ({esc(lid)}, {esc(pt)}, {esc(en)}, {esc(ph)}, {sy_sql}, {no_sql}, {mi_sql}, {i})"
            )
        lines.append(f"-- {key[0]} lesson {key[1]}: {LESSON_META[key][1]}\n")
        lines.append(
            "insert into public.phrases (lesson_id, phrase, translation, phonetic, syllable_breakdown, pronunciation_notes, common_mistakes, sort_order) values\n"
        )
        lines.append(",\n".join(ph_lines))
        lines.append(";\n\n")

    lines.append("commit;\n")
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {out} ({len(PHRASES)} lessons, {sum(len(v) for v in PHRASES.values())} phrases)")


if __name__ == "__main__":
    main()
