# Phrase rows: (pt, en, phonetic, syllable_breakdown, pronunciation_notes, common_mistakes)
# European Portuguese (Portugal) focus — practical for Americans relocating.

PHRASES = {
    ("A1", 1): [
        (
            "Bom dia",
            "Good morning",
            "bohng DEE-uh",
            "bom · dia",
            "Nasal vowel in bom; dia ends open like dee-uh, not a hard American R.",
            "Flapping an American R at the end of dia.",
        ),
        (
            "Boa tarde",
            "Good afternoon",
            "BOH-uh TAR-dee",
            "boa · tar · de",
            "Two light beats; keep r soft on the tongue, not American R.",
            "Stressing it like good AFTERnoon.",
        ),
        (
            "Boa noite",
            "Good evening / goodnight",
            "BOH-uh NOYT",
            "boa · noi · te",
            "Short, clear vowels; avoid extra sing-song from Brazilian media.",
            "Dragging noite into three slow syllables.",
        ),
        (
            "Por favor",
            "Please",
            "poor fah-VOHR",
            "por · fa · vor",
            "Stress the last syllable; European por is less round than Spanish.",
            "Over-rounding por like Spanish.",
        ),
        (
            "Obrigado / Obrigada",
            "Thank you (m/f)",
            "oh-bree-GAH-doo / dah",
            "o · bri · ga · do / da",
            "Stress on ga; keep endings clear.",
            "Using a long Brazilian-style melody by habit.",
        ),
        (
            "Desculpe",
            "Excuse me / sorry",
            "desh-KOOL-puh",
            "des · cul · pe",
            "C before u sounds like k; keep it short and polite.",
            "Pronouncing cul like English culp.",
        ),
        (
            "Com licença",
            "Excuse me (passing)",
            "kong lee-SEN-suh",
            "com · li · cen · ça",
            "Ç in Portugal is typically like s, not ch.",
            "Ch like church for licença.",
        ),
        (
            "Fala inglês?",
            "Do you speak English?",
            "FAH-luh een-GLAYSH?",
            "fa · la · in · glês",
            "Rising intonation; nasal ê in inglês.",
            "Flat statement intonation that sounds blunt.",
        ),
        (
            "Sou americano / americana",
            "I am American (m/f)",
            "soh ah-meh-ree-KAH-noo / nah",
            "sou · a · me · ri · ca · no / na",
            "Stress on ca; keep vowels bright.",
            "Heavy American R in americano.",
        ),
        (
            "Estou a aprender português",
            "I am learning Portuguese",
            "ehs-TOW ah ah-prehn-DEHR poor-too-GAYSH",
            "es · tou · a · ap · ren · der · por · tu · guês",
            "Link a aprender; nasal ês at the end of português.",
            "Swallowing the final nasal in português.",
        ),
    ],
    ("A1", 2): [
        (
            "Um café, por favor",
            "A coffee, please",
            "oong kah-FEH poor fah-VOHR",
            "um · ca · fé · por · fa · vor",
            "Um nasalizes slightly before café.",
            "Saying OOm with a long English oo.",
        ),
        (
            "Um café pingado",
            "Coffee with a drop of milk",
            "oong kah-FEH peen-GAH-doo",
            "um · ca · fé · pin · ga · do",
            "Very common in Portugal; light ending on do.",
            "Guessing pingado means ping.",
        ),
        (
            "Uma meia de leite",
            "A latte-style coffee",
            "OO-muh MAY-uh duh LAY-tuh",
            "u · ma · mei · a · de · lei · te",
            "Meia de leite is local phrasing, not Brazilian café com leite.",
            "Ordering latte and expecting the same word everywhere.",
        ),
        (
            "Para aqui",
            "For here",
            "PAH-ruh ah-KEE",
            "pa · ra · a · qui",
            "Short, clear; r stays light.",
            "Para like English para-golf.",
        ),
        (
            "Para levar",
            "To go",
            "PAH-ruh leh-VAHR",
            "pa · ra · le · var",
            "Stress on var; European r.",
            "American flap R in levar.",
        ),
        (
            "Sem açúcar",
            "Without sugar",
            "seng ah-SOO-kar",
            "sem · a · çú · car",
            "Sem is nasal; ç like s.",
            "Hard c like k in sugar.",
        ),
        (
            "Traga o talão, por favor",
            "Bring the receipt, please",
            "TRAH-guh oo tah-LOWN poor fah-VOHR",
            "tra · ga · o · ta · lão · por · fa · vor",
            "Talão is everyday receipt wording in Portugal.",
            "Using only recibo and confusing locals slightly.",
        ),
        (
            "Quanto é?",
            "How much is it?",
            "KWAHN-too eh?",
            "quan · to · é",
            "Short vowels; rising intonation on é.",
            "English how MUCH is IT stress pattern.",
        ),
        (
            "Pode ser com multibanco?",
            "Can I pay by debit card?",
            "POH-dee sehr kong mool-tee-BAHN-koo?",
            "po · de · ser · com · mul · ti · ban · co",
            "Multibanco is the Portuguese network name.",
            "Saying only cartão without enough context.",
        ),
        (
            "Só isto, obrigado",
            "That is all, thank you",
            "soh EESH-too oh-bree-GAH-doo",
            "só · is · to · o · bri · ga · do",
            "Isto with crisp s in European Portuguese.",
            "Dragging obrigado into a long song.",
        ),
    ],
    ("A1", 3): [
        (
            "Onde fica a estação de metro?",
            "Where is the metro station?",
            "OHN-dee FEE-kuh ah es-tah-SOWN deh MEH-troo?",
            "on · de · fi · ca · es · ta · ção · de · me · tro",
            "Nasal ão in estação; keep r soft.",
            "Heavy American R in metro.",
        ),
        (
            "É perto daqui?",
            "Is it near here?",
            "eh PEHR-too dah-KEE?",
            "é · per · to · da · qui",
            "Perto with a light tapped r.",
            "Making perto rhyme with burrito.",
        ),
        (
            "À direita",
            "To the right",
            "ah dee-RAY-tuh",
            "à · di · rei · ta",
            "Stress on rei; à is short.",
            "English die-RIGHT-uh stress.",
        ),
        (
            "À esquerda",
            "To the left",
            "ah shkehr-DUH",
            "à · es · quer · da",
            "Esqu- flows quickly; final a is light.",
            "Pronouncing es like English ess.",
        ),
        (
            "Um bilhete de ida e volta, por favor",
            "A round-trip ticket, please",
            "oong bil-YEH-tee deh EE-duh ee VOHL-tuh poor fah-VOHR",
            "um · bil · he · te · de · i · da · e · vol · ta",
            "Bilhete is standard in Portugal for tickets.",
            "Saying only ticket in English.",
        ),
        (
            "Para o aeroporto",
            "To the airport",
            "PAH-ruh oo ah-eh-roh-POR-too",
            "pa · ra · o · a · e · ro · por · to",
            "European r at the end stays soft, not growled.",
            "American hard R in aeroporto.",
        ),
        (
            "O comboio atrasa?",
            "Is the train late?",
            "ooh kom-BOY-oo ah-trah-ZAH?",
            "o · com · boi · o · a · tra · sa",
            "Comboio is train in Portugal; not trem.",
            "Using trem and sounding Brazilian.",
        ),
        (
            "Onde posso validar o passe?",
            "Where can I validate the pass?",
            "OHN-deh POH-soo vah-lee-DAR oo pah-suh?",
            "on · de · pos · so · va · li · dar · o · pas · se",
            "Validator machines are common; keep vowels clear.",
            "Validating with an English v sound too sharp.",
        ),
        (
            "Há uma paragem aqui perto?",
            "Is there a stop near here?",
            "ah OO-muh pah-RAH-zhayng ah-KEE PEHR-too?",
            "há · u · ma · pa · ra · gem · a · qui · per · to",
            "Paragem is bus stop wording in Portugal.",
            "Using parada as in Spanish.",
        ),
        (
            "Pode repetir, por favor?",
            "Can you repeat, please?",
            "POH-dee heh-peh-TEER poor fah-VOHR?",
            "po · de · re · pe · tir · por · fa · vor",
            "Polite tone; pode is softer than a command.",
            "Intonation that sounds impatient.",
        ),
    ],
    ("A1", 4): [
        (
            "Quanto custa?",
            "How much does it cost?",
            "KWAHN-too KOOSH-tuh?",
            "quan · to · cus · ta",
            "C before u is like k; short vowels.",
            "Cust-uh with English cust.",
        ),
        (
            "É caro",
            "It is expensive",
            "eh KAH-roo",
            "é · ca · ro",
            "Open ah vowel; light r ending.",
            "English carry-O.",
        ),
        (
            "Aceita multibanco?",
            "Do you take debit card?",
            "ah-SAY-tuh mool-tee-BAHN-koo?",
            "a · cei · ta · mul · ti · ban · co",
            "Common question in shops; calm intonation.",
            "Saying credit card only and assuming.",
        ),
        (
            "Pode falar mais devagar?",
            "Can you speak more slowly?",
            "POH-deh fah-LAR mah-eezh deh-vah-GAHR?",
            "po · de · fa · lar · mais · de · va · gar",
            "Mais devagar is a polite fix for fast speech.",
            "Shouting slower slower in English.",
        ),
        (
            "A que horas abre?",
            "What time does it open?",
            "ah keh OH-rash AH-bruh?",
            "a · que · ho · ras · a · bre",
            "Nasal plural horas; crisp b in abre.",
            "English what TIME does it OPEN stress.",
        ),
        (
            "A que horas fecha?",
            "What time does it close?",
            "ah keh OH-rash FAY-shuh?",
            "a · que · ho · ras · fe · cha",
            "Ch like sh in many European Portuguese contexts.",
            "Ch like church.",
        ),
        (
            "Hoje",
            "Today",
            "OH-zhe",
            "ho · je",
            "Soft zh-like j in many accents; keep it short.",
            "English hoe-jay diphthong.",
        ),
        (
            "Amanhã",
            "Tomorrow",
            "ah-mahn-YAHNG",
            "a · man · hã",
            "Nasal ã; nh like ny in canyon.",
            "Ignoring the nasal quality.",
        ),
        (
            "Desculpe, não percebi",
            "Sorry, I did not understand",
            "desh-KOOL-puh,nowng pehr-say-BEE",
            "des · cul · pe · não · per · ce · bi",
            "Não nasal; percebi stress on ce.",
            "Saying no comprendo from Spanish habit.",
        ),
        (
            "Pode escrever aqui?",
            "Can you write it here?",
            "POH-deh eesh-kreh-VEHR ah-KEE?",
            "po · de · es · cre · ver · a · qui",
            "Useful for addresses; crisp s in escrever.",
            "English write it HERE command tone.",
        ),
    ],
    ("A1", 5): [
        (
            "Bom dia, preciso de ajuda",
            "Good morning, I need help",
            "bohng DEE-uh preh-SEE-zoo deh ah-ZHOO-dah",
            "bom · dia · pre · ci · so · de · a · ju · da",
            "Ajuda with soft j in many EP pronunciations.",
            "Hard j like judge in ajuda.",
        ),
        (
            "É sem receita?",
            "Is it over the counter?",
            "eh seng heh-SAY-tuh?",
            "é · sem · re · cei · ta",
            "Receita means prescription; sem receita is common phrasing.",
            "Translating literally with English idiom.",
        ),
        (
            "Para dor de cabeça",
            "For a headache",
            "PAH-ruh dohr deh kah-BEH-suh",
            "pa · ra · dor · de · ca · be · ça",
            "Cabeça with soft ç like s.",
            "Hard c in cabeça.",
        ),
        (
            "Para a alergia",
            "For allergies",
            "PAH-ruh ah ah-lehr-ZHEE-uh",
            "pa · ra · a · a · ler · gi · a",
            "Gentle tone; keep gi clear.",
            "English allergy vowels.",
        ),
        (
            "Só para uso externo",
            "For external use only",
            "soh PAH-ruh OO-zoo ehs-TEHR-noo",
            "só · pa · ra · u · so · es · ter · no",
            "Useful label reading; slow and clear.",
            "Guessing externo from Spanish false friends.",
        ),
        (
            "Tem efeitos secundários?",
            "Does it have side effects?",
            "teng eh-FAY-toosh seh-koon-DAH-ree-oosh?",
            "tem · e · fei · tos · se · cun · da · ri · os",
            "Plural adjective agreement; nasal tem.",
            "Rushing the question and sounding sharp.",
        ),
        (
            "Obrigado, tenha um bom dia",
            "Thank you, have a good day",
            "oh-bree-GAH-doo, TEN-yuh oong bohng DEE-uh",
            "o · bri · ga · do · ten · ha · um · bom · dia",
            "Polite close; tenha is formal friendly.",
            "Over-casual thanks mate.",
        ),
        (
            "Queria o genérico, se houver",
            "I would like the generic, if available",
            "kreh-REE-uh oo zheh-NAY-ree-koo seh oh-VEHR",
            "que · ri · a · o · ge · né · ri · co · se · ho · ver",
            "Useful at pharmacy counters; verify with pharmacist.",
            "Demanding genérico like a command.",
        ),
        (
            "Posso tomar isto com outros medicamentos?",
            "Can I take this with other medications?",
            "POH-soo too-MAR EESH-too kong OH-troosh meh-dee-kah-MEN-toosh?",
            "pos · so · to · mar · is · to · com · ou · tros · me · di · ca · men · tos",
            "Ask a professional; this phrase is only for communication practice.",
            "Treating phrase practice as medical certainty.",
        ),
        (
            "Obrigado pela ajuda",
            "Thanks for the help",
            "oh-bree-GAH-doo PEH-luh ah-ZHOO-dah",
            "o · bri · ga · do · pe · la · a · ju · da",
            "Warm, short close; pela links smoothly.",
            "Leaving without acknowledging staff.",
        ),
    ],
    ("A2", 1): [
        (
            "Gostaria de visitar o apartamento",
            "I would like to visit the apartment",
            "gosh-tah-REE-uh deh vee-zee-TAR oh ah-part-ah-MEN-too",
            "gos · ta · ri · a · de · vi · si · tar · o · a · par · ta · men · to",
            "Smooth link de visitar; stress lightly on men.",
            "English APARTment stress.",
        ),
        (
            "Qual é a renda mensal?",
            "What is the monthly rent?",
            "kwahl eh ah HEN-dah men-SAHL?",
            "qual · é · a · ren · da · men · sal",
            "Renda with clear EH vowel; mensal crisp.",
            "American flap R in rent.",
        ),
        (
            "As despesas estão incluídas?",
            "Are utilities included?",
            "ash des-PEH-zash es-TOWN een-kloo-EE-dash?",
            "as · des · pe · sas · es · tão · in · cluí · das",
            "Nasal estão; plural das clear.",
            "Swallowing nasal ão.",
        ),
        (
            "Há elevador?",
            "Is there an elevator?",
            "ah eh-leh-vah-DOHR?",
            "há · e · le · va · dor",
            "Há is short; stress on dor.",
            "Silent h confusion—still pronounce lightly.",
        ),
        (
            "Posso marcar uma segunda visita?",
            "Can I schedule a second visit?",
            "POH-soo mar-KAR OO-muh seh-GOON-duh vee-ZEE-tuh?",
            "pos · so · mar · car · u · ma · se · gun · da · vi · si · ta",
            "Polite posso; even rhythm.",
            "Stressing SECOND like English.",
        ),
        (
            "O aquecimento funciona?",
            "Does the heating work?",
            "ooh ah-keh-see-MEN-too foon-see-OH-nuh?",
            "o · a · que · ci · men · to · fun · ci · o · na",
            "Nasal ão in funciona; measured question.",
            "Heating with English heat-ing stress.",
        ),
        (
            "Há humidade nas paredes?",
            "Is there damp on the walls?",
            "ah oo-mee-DAH-deh nash pah-REH-desh?",
            "há · u · mi · da · de · nas · pa · re · des",
            "Useful in older buildings; plural des crisp.",
            "Ignoring nasal nas.",
        ),
        (
            "O registo predial está disponível?",
            "Is the building energy certificate available?",
            "ooh heh-ZHISH-too preh-dee-AHL es-TAH dees-poh-NEE-vel?",
            "o · re · gis · to · pre · di · al · es · tá · dis · po · ni · vel",
            "Administrative term—ask slowly if needed.",
            "Guessing English acronym only.",
        ),
        (
            "Posso tirar fotos?",
            "May I take photos?",
            "POH-soo tee-RAR FOH-too?",
            "pos · so · ti · rar · fo · tos",
            "Polite request; plural fotos.",
            "Demanding photos now in English tone.",
        ),
        (
            "Envio um email com as minhas dúvidas",
            "I will send an email with my questions",
            "ayn-VEE-oo oong ee-MAY-ee kong ash MEE-nyash DOO-vee-dush",
            "en · vi · o · um · e · mail · com · as · mi · nhas · dú · vi · das",
            "Email is commonly said ee-mail; keep calm close.",
            "Overlong formal letter tone out loud.",
        ),
    ],
    ("A2", 2): [
        (
            "Um quilo de maçãs, por favor",
            "One kilo of apples, please",
            "oong KEE-loo deh mah-SAHNGS poor fah-VOHR",
            "um · qui · lo · de · ma · çãs · por · fa · vor",
            "Nasal ãs in maçãs; ç like s.",
            "English apple vowels in maçãs.",
        ),
        (
            "Pode pesar?",
            "Can you weigh it?",
            "POH-deh peh-ZAR?",
            "po · de · pe · zar",
            "Stress on second syllable of pesar.",
            "American Z in weigh.",
        ),
        (
            "Preciso de um saco",
            "I need a bag",
            "preh-SEE-zoo deh oong SAH-koo",
            "pre · ci · so · de · um · sa · co",
            "Saco with open o; common in Portugal.",
            "English sack-oh diphthong.",
        ),
        (
            "Onde está o talão?",
            "Where is the receipt?",
            "OHN-dee es-TAH ooh tah-LOWN?",
            "on · de · es · tá · o · ta · lão",
            "Talão is everyday receipt wording.",
            "Receipt with English RE-seat.",
        ),
        (
            "Só isto, obrigado",
            "That is all, thank you",
            "soh EESH-too oh-bree-GAH-doo",
            "só · is · to · o · bri · ga · do",
            "Crisp isto; short close.",
            "Brazilian-style long obrigado.",
        ),
        (
            "Tem pão integral?",
            "Do you have wholemeal bread?",
            "teng powng een-teh-GRAHL?",
            "tem · pão · in · te · gral",
            "Pão nasal; integral stress on gra.",
            "Pan like Spanish pan.",
        ),
        (
            "Queria queijos da serra, por favor",
            "I would like mountain cheeses, please",
            "kreh-REE-uh KAY-zhoozh dah SEH-ruh poor fah-VOHR",
            "que · ri · a · quei · jos · da · se · rra · por · fa · vor",
            "Queijos with zh-like j in many accents.",
            "Hard j in queijos.",
        ),
        (
            "Onde fica a balança?",
            "Where is the scale?",
            "OHN-dee FEE-kuh ah bah-LAHNG-suh?",
            "on · de · fi · ca · a · ba · lan · ça",
            "Ç like s; useful in mercado.",
            "Balança like balance in English.",
        ),
        (
            "Pode cortar mais fino?",
            "Can you slice it thinner?",
            "POH-deh kor-TAR mah-eezh FEE-noo?",
            "po · de · cor · tar · mais · fi · no",
            "Polite request at deli counters.",
            "Commanding cut it thinner.",
        ),
        (
            "Levo num saco reutilizável",
            "I will take a reusable bag",
            "LEH-voo noong SAH-koo ray-oo-tee-lee-ZAH-vel",
            "le · vo · num · sa · co · re · u · ti · li · zá · vel",
            "Environmental phrasing is common in shops.",
            "Reutilizável with English util stress.",
        ),
    ],
    ("A2", 3): [
        (
            "Queria marcar uma consulta",
            "I would like to book an appointment",
            "kreh-REE-uh mar-KAR OO-muh kon-SOOL-tuh",
            "que · ri · a · mar · car · u · ma · con · sul · ta",
            "Soft queria; polite conditional feel.",
            "Hard English WANT.",
        ),
        (
            "Tem disponibilidade na próxima semana?",
            "Do you have availability next week?",
            "teng dees-poh-nee-bee-lee-DAH-deh nah PROK-see-muh seh-NAH-nuh?",
            "tem · dis · po · ni · bi · li · da · de · na · pró · xi · ma · se · ma · na",
            "Nasal tem; próxima flows.",
            "Stressing AVAILability.",
        ),
        (
            "Pode confirmar o endereço?",
            "Can you confirm the address?",
            "POH-deh kon-feer-MAR oo en-deh-REH-soo?",
            "po · de · con · fir · mar · o · en · de · re · ço",
            "Endereço with ç like s.",
            "English address vowels.",
        ),
        (
            "Preciso remarcar",
            "I need to reschedule",
            "preh-SEE-zoo heh-mar-KAR",
            "pre · ci · so · re · mar · car",
            "Linked remarcar keeps momentum.",
            "Awkward pause between syllables.",
        ),
        (
            "Obrigado pela chamada",
            "Thank you for the call",
            "oh-bree-GAH-doo PEH-luh shah-MAH-duh",
            "o · bri · ga · do · pe · la · cha · ma · da",
            "Ch like sh in chamada in many EP pronunciations.",
            "Ch like church.",
        ),
        (
            "Estou com uma urgência",
            "I have an urgent situation",
            "ehs-TONG kong OO-muh oor-ZHEN-syuh",
            "es · tou · com · u · ma · ur · gen · cia",
            "Nasal estou; keep tone calm, not dramatic.",
            "Shouting urgent in English.",
        ),
        (
            "Pode enviar confirmação por email?",
            "Can you send confirmation by email?",
            "POH-deh en-vee-AR kon-feer-mah-SOWN poor ee-MAYL?",
            "po · de · en · vi · ar · con · fir · ma · ção · por · e · mail",
            "Nasal ção; ee-mail common.",
            "Demanding confirmation now.",
        ),
        (
            "Qual é o melhor horário?",
            "What is the best time?",
            "kwahl eh oo mel-YOHR oh-ree-AH-ree-oo?",
            "qual · é · o · mel · hor · o · ho · ri · o",
            "Horário with clear o endings.",
            "English BEST time stress.",
        ),
        (
            "Posso ficar em lista de espera?",
            "Can I join the waiting list?",
            "POH-soo fee-KAR ayng LEESH-tah deh eesh-peh-RAH?",
            "pos · so · fi · car · em · lis · ta · de · es · pe · ra",
            "Lista de espera is common phrasing.",
            "Waiting list translated word-by-word oddly.",
        ),
        (
            "Obrigado, fico à espera",
            "Thanks, I will wait",
            "oh-bree-GAH-doo, FEE-koo ah eesh-PEH-ruh",
            "o · bri · ga · do · fi · co · à · es · pe · ra",
            "Polite close; à espera is natural.",
            "Leaving abruptly without thanks.",
        ),
    ],
    ("A2", 4): [
        (
            "Queria levantar numerário",
            "I would like to withdraw cash",
            "kreh-REE-uh leh-vahn-TAR noo-meh-RAH-ree-oo",
            "que · ri · a · le · van · tar · nu · me · rá · ri · o",
            "Numerário is common wording in Portugal for cash.",
            "Using only dinheiro and confusing nuance.",
        ),
        (
            "Onde fica o multibanco?",
            "Where is the ATM?",
            "OHN-dee FEE-koo oo mool-tee-BAHN-koo?",
            "on · de · fi · co · o · mul · ti · ban · co",
            "Multibanco is the local network name.",
            "Saying ATM in English only.",
        ),
        (
            "Quero fazer um pagamento",
            "I want to make a payment",
            "KEH-roo fah-ZEHR oong pah-gah-MEN-too",
            "que · ro · fa · zer · um · pa · ga · men · to",
            "Keep quero polite with soft tone.",
            "Quero sounding like a demand.",
        ),
        (
            "Preciso do IBAN",
            "I need the IBAN",
            "preh-SEE-zoo doo ee-BAHN",
            "pre · ci · so · do · I · BAN",
            "Spell slowly if needed; acronym stays clear.",
            "Yelling IBAN across the room.",
        ),
        (
            "Pode imprimir o comprovativo?",
            "Can you print the proof?",
            "POH-deh im-pree-MEER oo kom-proo-vah-TEE-voo?",
            "po · de · im · pri · mir · o · com · pro · va · ti · vo",
            "Comprovativo is common for printed proof.",
            "Proof with English roof vowel.",
        ),
        (
            "Ainda não recebi o cartão",
            "I have not received the card yet",
            "ah-EEN-dahnowng heh-seh-BEE oo kar-TOWNG",
            "a · in · da · não · re · ce · bi · o · car · tão",
            "Nasal ão in cartão; calm tone.",
            "Blaming the staff aggressively.",
        ),
        (
            "Queria falar com um gestor",
            "I would like to speak with a manager",
            "kreh-REE-uh fah-LAR kong oong zheh-STOHR",
            "que · ri · a · fa · lar · com · um · zes · tor",
            "Gestor is common in banks; polite request.",
            "Demanding manager now in English.",
        ),
        (
            "Há fila?",
            "Is there a line?",
            "ah FEE-luh?",
            "há · fi · la",
            "Short, practical; rising intonation.",
            "Is there a line translated too wordy.",
        ),
        (
            "Posso esperar aqui?",
            "May I wait here?",
            "POH-soo eesh-peh-RAR ah-KEE?",
            "pos · so · es · pe · rar · a · qui",
            "Polite; useful in busy counters.",
            "Blocking the queue without asking.",
        ),
        (
            "Obrigado pela ajuda",
            "Thanks for the help",
            "oh-bree-GAH-doo PEH-luh ah-ZHOO-dah",
            "o · bri · ga · do · pe · la · a · ju · da",
            "Warm close after a bank visit.",
            "Leaving without acknowledging staff.",
        ),
    ],
    ("A2", 5): [
        (
            "Queria enviar uma encomenda",
            "I would like to send a parcel",
            "kreh-REE-uh en-vee-AR OO-muh ayng-koo-MEN-duh",
            "que · ri · a · en · vi · ar · u · ma · en · co · men · da",
            "Encomenda is parcel; smooth linking.",
            "Package with English pack-edge.",
        ),
        (
            "Para os Estados Unidos",
            "To the United States",
            "PAH-roo oosh ehs-TAH-dooz oo-NEE-dooz",
            "pa · ra · os · es · ta · dos · u · ni · dos",
            "Useful for shipping labels; clear vowels.",
            "American state names inserted awkwardly.",
        ),
        (
            "Com seguro?",
            "With insurance?",
            "kong seh-GOO-roo?",
            "com · se · gu · ro",
            "Rising question; o is open.",
            "Seguro stressed like English secure.",
        ),
        (
            "Quanto custa o envio?",
            "How much is shipping?",
            "KWAHN-too KOOSH-tuh oo ayn-VEE-oo?",
            "quan · to · cus · ta · o · en · vi · o",
            "Short vowels; clear question.",
            "Shipping with English ship-ping stress.",
        ),
        (
            "Preciso de um número de tracking",
            "I need a tracking number",
            "preh-SEE-zoo deh oong NOO-meh-roo deh TRACK-ing",
            "pre · ci · so · de · um · nú · me · ro · de · tracking",
            "Borrowed tracking is common; keep PT rhythm.",
            "English TRACK-ing emphasis on every syllable.",
        ),
        (
            "Onde fica a fila para levantar encomendas?",
            "Where is the line to pick up parcels?",
            "OHN-dee FEE-kuh ah FEE-luh PAH-ruh leh-vahn-TAR ayng-koo-MEN-dash?",
            "on · de · fi · ca · a · fi · la · pa · ra · le · van · tar · en · com · en · das",
            "Plural das; keep nasals distinct.",
            "Mumbling nasals together.",
        ),
        (
            "Posso assinar aqui?",
            "May I sign here?",
            "POH-soo ah-see-NAR ah-KEE?",
            "pos · so · a · si · nar · a · qui",
            "Assinar with crisp s in European Portuguese.",
            "Sign with English long i.",
        ),
        (
            "A encomenda chegou danificada",
            "The parcel arrived damaged",
            "ah ayng-koo-MEN-dah sheh-GOH dah-nee-fee-KAH-dah",
            "a · en · co · men · da · che · gou · da · ni · fi · ca · da",
            "Clear complaint tone without shouting.",
            "Angry English tone from the start.",
        ),
        (
            "Queria reclamar uma encomenda atrasada",
            "I would like to complain about a delayed parcel",
            "kreh-REE-uh heh-klah-MAR OO-muh ayng-koo-MEN-dah ah-trah-ZAH-dah",
            "que · ri · a · re · cla · mar · u · ma · en · co · men · da · a · tra · za · da",
            "Reclamar is firm but can stay polite.",
            "Starting with you people energy.",
        ),
        (
            "Obrigado, tenha um bom dia",
            "Thank you, have a good day",
            "oh-bree-GAH-doo, TEN-yuh oong bohng DEE-uh",
            "o · bri · ga · do · ten · ha · um · bom · dia",
            "Polite close after Correios.",
            "Leaving without thanks.",
        ),
    ],
    ("B1", 1): [
        (
            "Há um problema com a água",
            "There is a problem with the water",
            "ah oong proo-BLEH-muh kong ah AH-gwah",
            "há · um · pro · ble · ma · com · a · á · gua",
            "Open a in água; há is short.",
            "English problem vowel.",
        ),
        (
            "A pressão está fraca",
            "The pressure is low",
            "ah preh-SOWN es-TAH FRAH-kuh",
            "a · pres · são · es · tá · fra · ca",
            "Nasal pressão; fraca delicate ending.",
            "Stressing LOW English-style.",
        ),
        (
            "Já avisei o senhorio",
            "I already informed the landlord",
            "zhah ah-vee-ZAY ooh seh-NYOHR-yoo",
            "já · a · vi · sei · o · se · nho · ri · o",
            "Senhorio flows; nh like ny in canyon.",
            "Hard j like judge in já.",
        ),
        (
            "Podem enviar alguém hoje?",
            "Can you send someone today?",
            "POH-deng en-vee-AR ahl-GAYNG oy-zhe?",
            "po · dem · en · vi · ar · al · guem · ho · je",
            "Nasal podem; hoje soft zh-like j.",
            "English today stress.",
        ),
        (
            "Preciso disto resolvido rapidamente",
            "I need this resolved quickly",
            "preh-SEE-zoo DEESH-too reh-zol-VEE-doo hah-pee-dah-MEN-teh",
            "pre · ci · so · dis · to · re · sol · vi · do · ra · pi · da · men · te",
            "Even pace; avoid shouting urgency.",
            "Rushing consonants into a blur.",
        ),
        (
            "O barulho continua durante a noite",
            "The noise continues during the night",
            "ooh bah-ROOL-yoo kon-tee-NOO-uh doo-RAHN-teh ah NOYT",
            "o · ba · ru · lho · con · ti · nua · du · ran · te · a · noi · te",
            "Barulho is common complaint vocabulary.",
            "English noise with oy diphthong.",
        ),
        (
            "Não é aceitável para mim",
            "It is not acceptable to me",
            "nowng eh ah-say-TAH-vel PAH-ruh meeng",
            "não · é · a · cei · tá · vel · pa · ra · mim",
            "Nasal não; keep tone firm but calm.",
            "Monotone that sounds rude.",
        ),
        (
            "Podemos combinar uma visita técnica?",
            "Can we schedule a technical visit?",
            "poh-DEH-moosh kom-bee-NAHR OO-muh vee-ZEE-tuh TEK-nee-kuh?",
            "po · de · mos · com · bi · nar · u · ma · vi · si · ta · té · ni · ca",
            "Polite question; técnica clear.",
            "TECH-nical English stress.",
        ),
        (
            "Quero deixar registado por escrito",
            "I want this logged in writing",
            "KEH-roo day-SHAR heh-zheesh-TAH-doo poor eesh-KREE-too",
            "que · ro · deix · ar · re · gis · ta · do · por · es · cri · to",
            "Registado is common wording; calm tone.",
            "Demanding written proof aggressively.",
        ),
        (
            "Obrigado pela vossa paciência",
            "Thank you for your patience",
            "oh-bree-GAH-doo PEH-luh VOH-sah pah-see-EN-syuh",
            "o · bri · ga · do · pe · la · vos · sa · pa · ci · en · cia",
            "Vossa formal plural; useful with services.",
            "Too slangy for a formal context.",
        ),
    ],
    ("B1", 2): [
        (
            "O contrato prevê estas reparações",
            "The contract covers these repairs",
            "ooh kon-TRA-too preh-VAY ESH-tash heh-pah-rah-SOYSH",
            "o · con · tra · to · pre · vê · es · tas · re · pa · ra · ções",
            "Nasal plural ções; measured tone.",
            "English CONtract stress.",
        ),
        (
            "Gostaria de pedir um prazo",
            "I would like to request a deadline",
            "gosh-tah-REE-uh deh peh-DEER oong PRAH-zoo",
            "gos · ta · ri · a · de · pe · dir · um · pra · zo",
            "Prazo stress on first syllable.",
            "English praise-oh.",
        ),
        (
            "Quando pode ser a vistoria?",
            "When can the inspection be?",
            "KWAHN-doo POH-deh sehr ah veesh-toh-REE-uh?",
            "quan · do · po · de · ser · a · vis · to · ri · a",
            "Vistoria is common for inspections; rising question.",
            "Using only inspection in English at the counter.",
        ),
        (
            "Preciso disto por escrito",
            "I need this in writing",
            "preh-SEE-zoo DEESH-too poor eesh-KREE-too",
            "pre · ci · so · dis · to · por · es · cri · to",
            "Escrito crisp s in European Portuguese.",
            "Guessing silent letters.",
        ),
        (
            "Obrigado pela compreensão",
            "Thanks for your understanding",
            "oh-bree-GAH-doo PEH-luh kom-pree-en-SOWN",
            "o · bri · ga · do · pe · la · com · pre · en · são",
            "Warm, calm closing; nasal são.",
            "Overly casual thanks dude.",
        ),
        (
            "Há infiltrações no telhado?",
            "Are there leaks in the roof?",
            "ah een-fil-trah-SOYSH noo tel-YAH-doo?",
            "há · in · fil · tra · ções · no · te · lha · do",
            "Telhado with lh like ly in million in many accents.",
            "Hard th in roof thinking English.",
        ),
        (
            "O condomínio pode intervir?",
            "Can the condominium management intervene?",
            "ooh kon-doo-MEEN-yoo POH-deh een-tehr-VEER?",
            "o · con · do · mí · ni · o · po · de · in · ter · vir",
            "Condomínio is common in Portugal; polite question.",
            "HOA English acronym only.",
        ),
        (
            "Queria registar uma reclamação",
            "I would like to register a complaint",
            "kreh-REE-uh heh-zheesh-TAR OO-muh heh-klah-mah-SOWN",
            "que · ri · a · re · gis · tar · u · ma · re · cla · ma · ção",
            "Nasal ção; keep professional tone.",
            "Starting with I am going to sue.",
        ),
        (
            "Podemos alinhar expectativas?",
            "Can we align expectations?",
            "poh-DEH-moosh ah-lee-NYAR eks-pek-tah-TEE-vash?",
            "po · de · mos · a · lin · har · ex · pec · ta · ti · vas",
            "Borrowed alinhar is common in workplaces; keep PT melody.",
            "Corporate English intonation on every word.",
        ),
        (
            "Fico à espera da vossa resposta",
            "I will await your reply",
            "FEE-koo ah eesh-PEH-ruh dah VOH-shah heh-SPOOSH-tuh",
            "fi · co · à · es · pe · ra · da · vos · sa · res · pos · ta",
            "Formal plural vossa; polite close.",
            "Ghosting without a closing line.",
        ),
    ],
    ("B1", 3): [
        (
            "Sinto dores aqui",
            "I feel pain here",
            "SEEN-too DOH-reez ah-KEE",
            "sin · to · do · res · a · qui",
            "Dores plural with crisp s.",
            "English pains diphthong.",
        ),
        (
            "Começou há dois dias",
            "It started two days ago",
            "koh-meh-SOH ah doysh DEE-ush",
            "co · me · çou · há · dois · di · as",
            "Dois with European s/z pattern in connected speech.",
            "Hard z everywhere.",
        ),
        (
            "A minha alergia é a pólen",
            "My allergy is pollen",
            "ah MEE-nyah ah-lehr-ZHEE-uh eh ah POH-leng",
            "a · mi · nha · a · ler · gi · a · é · a · pó · len",
            "Nasal len; gentle delivery.",
            "English allergy stress.",
        ),
        (
            "O cão não come desde ontem",
            "The dog has not eaten since yesterday",
            "ooh kowngnowng KOH-mee DEHZ-dee ON-teng",
            "o · cão · não · co · me · des · de · on · tem",
            "Multiple nasals—keep them distinct.",
            "Flattening nasals into one blob.",
        ),
        (
            "Preciso de uma receita",
            "I need a prescription",
            "preh-SEE-zoo deh OO-muh heh-SAY-tuh",
            "pre · ci · so · de · u · ma · re · cei · ta",
            "Receita stress on cei; verify with clinician.",
            "English recipe vowel.",
        ),
        (
            "Estou com febre e tonturas",
            "I have a fever and dizziness",
            "ehs-TONG kong FEH-bree ee toon-TOO-rush",
            "es · tou · com · fe · bre · e · ton · tu · ras",
            "Educational phrasing only—not diagnosis.",
            "Listing symptoms like a WebMD monologue.",
        ),
        (
            "Queria marcar uma consulta de rotina",
            "I would like to book a routine appointment",
            "kreh-REE-uh mar-KAR OO-muh kon-SOOL-tuh deh roo-TEE-nuh",
            "que · ri · a · mar · car · u · ma · con · sul · ta · de · ro · ti · na",
            "Rotina with clear i vowels.",
            "Routine with English ROO-teen stress.",
        ),
        (
            "Posso trazer o meu número de utente?",
            "May I bring my patient number?",
            "POH-soo trah-ZEHR oo may-oo NOO-meh-roo deh oo-TEN-teh?",
            "pos · so · tra · zer · o · meu · nú · me · ro · de · u · ten · te",
            "Utente is common in SNS contexts; confirm locally.",
            "Patient with English PAY-shunt vowel.",
        ),
        (
            "Onde fica a receção?",
            "Where is reception?",
            "OHN-dee FEE-kuh ah heh-SEH-sown?",
            "on · de · fi · ca · a · re · ce · ção",
            "Receção spelling with ç; nasal ção.",
            "Reception with English shun ending.",
        ),
        (
            "Obrigado, tenha um bom dia",
            "Thank you, have a good day",
            "oh-bree-GAH-doo, TEN-yuh oong bohng DEE-uh",
            "o · bri · ga · do · ten · ha · um · bom · dia",
            "Polite close after a desk visit.",
            "Leaving abruptly.",
        ),
    ],
    ("B1", 4): [
        (
            "Bom dia, tenho uma marcação",
            "Good morning, I have an appointment",
            "bohng DEE-uh, TEN-yoo OO-muh mar-kah-SOWN",
            "bom · dia · ten · ho · u · ma · mar · ca · ção",
            "Marcação nasal; calm opener.",
            "Appointment with English AP-point-ment.",
        ),
        (
            "Ainda falta algum documento?",
            "Is any document still missing?",
            "ah-EEN-dah FAL-tah al-GOONG do-koo-MEN-too?",
            "a · in · da · fal · ta · al · gum · do · cu · men · to",
            "Rising intonation; polite check-in.",
            "Blunt what is missing.",
        ),
        (
            "Trago o comprovativo de morada",
            "I brought proof of address",
            "TRAH-goo oo kom-proo-vah-TEE-voo deh moh-RAH-duh",
            "tra · go · o · com · pro · va · ti · vo · de · mo · ra · da",
            "Even rhythm; official but friendly.",
            "Swallowing comprovativo.",
        ),
        (
            "Pode explicar estes campos outra vez?",
            "Can you explain these fields again?",
            "POH-deh eesh-plee-KAR ESH-teesh KAHM-poosh OH-truh vehsh?",
            "po · de · ex · pli · car · es · tes · cam · pos · ou · tra · vez",
            "Campos plural; second vez polite.",
            "Demanding explain it in English.",
        ),
        (
            "Não percebi o que falta",
            "I did not understand what is missing",
            "nowng pehr-say-BEE oo keh FAL-tuh",
            "não · per · ce · bi · o · que · fal · ta",
            "Não nasal; calm admission.",
            "Angry I do not understand.",
        ),
        (
            "Posso esperar na fila?",
            "May I wait in the line?",
            "POH-soo eesh-peh-RAR nah FEE-luh?",
            "pos · so · es · pe · rar · na · fi · la",
            "Useful in busy counters; polite.",
            "Blocking others without asking.",
        ),
        (
            "Queria pedir um número de senha",
            "I would like to request a ticket number",
            "kreh-REE-uh peh-DEER oong NOO-meh-roo deh SAY-nyuh",
            "que · ri · a · pe · dir · um · nú · me · ro · de · se · nha",
            "Senha here can mean ticket number contextually; confirm locally.",
            "Password meaning confusion without context.",
        ),
        (
            "Há acessibilidade neste balcão?",
            "Is there accessibility at this counter?",
            "ah ah-seh-see-bee-lee-DAH-deh NESH-teh bal-KOWNG?",
            "há · a · ces · si · bi · li · da · de · nes · te · bal · cão",
            "Nasal cão; respectful question.",
            "Accessibility with English accessibility stress.",
        ),
        (
            "Obrigado pela vossa ajuda",
            "Thank you for your help",
            "oh-bree-GAH-doo PEH-luh VOH-sah ah-ZHOO-dah",
            "o · bri · ga · do · pe · la · vos · sa · a · ju · da",
            "Formal plural vossa; warm close.",
            "Too informal for a counter context.",
        ),
        (
            "Boa tarde, até breve",
            "Good afternoon, see you soon",
            "BOH-uh TAR-dee, AH-teh BREH-veh",
            "boa · tar · de · a · té · bre · ve",
            "Short polite close when stepping away.",
            "See you soon with American drawl.",
        ),
    ],
    ("B1", 5): [
        (
            "O IUC vence este mês",
            "The vehicle tax is due this month",
            "ooh ee-oo-SEH VEN-seh ESH-teh mayng",
            "o · I · U · C · ven · ce · es · te · mês",
            "Acronyms spelled softly; mês nasal.",
            "Yelling I-U-C like a slogan.",
        ),
        (
            "Preciso marcar a inspeção periódica",
            "I need to book the periodic inspection",
            "preh-SEE-zoo mar-KAR ah een-speh-SOWN peh-ree-OH-dee-kuh",
            "pre · ci · so · mar · car · a · in · spe · ção · pe · ri · ó · di · ca",
            "Inspeção nasal; keep official tone calm.",
            "Inspection with English IN-spek-shun.",
        ),
        (
            "O carro falha ao arrancar",
            "The car struggles when starting",
            "ooh KAH-roo FAL-yah ow ah-rahn-KAR",
            "o · ca · rro · fal · ha · ao · a · ran · car",
            "Double r in carro; arrancar with light r.",
            "Carro with English car-O.",
        ),
        (
            "A luz do motor acendeu",
            "The engine warning light came on",
            "ah loosh doo moh-TOR ah-sen-DEO",
            "a · luz · do · mo · tor · a · cen · deu",
            "Motor with European o; calm report.",
            "Motor with English MO-tor stress.",
        ),
        (
            "Queria um orçamento para a reparação",
            "I would like a quote for the repair",
            "kreh-REE-uh oong ohr-sah-MEN-too PAH-ruh ah heh-pah-rah-SOWN",
            "que · ri · a · um · or · ça · men · to · pa · ra · a · re · pa · ra · ção",
            "Orçamento is common; nasal ção.",
            "Quote with English KWOTE vowel.",
        ),
        (
            "Posso deixar o carro durante a manhã?",
            "May I leave the car during the morning?",
            "POH-soo day-SHAR oo KAH-roo doo-RAHN-teh ah mahn-YAHNG?",
            "pos · so · deix · ar · o · ca · rro · du · ran · te · a · man · hã",
            "Nasal manhã; polite question.",
            "Manhã like English manna.",
        ),
        (
            "Há peças de origem europeia?",
            "Are the parts of European origin?",
            "ah PEH-sash deh oh-REE-zhayng ay-oo-roo-PAY-uh?",
            "há · pe · ças · de · o · ri · gem · eu · ro · pe · ia",
            "Useful phrasing; keep vowels clear.",
            "Europe with English YOOR-up stress.",
        ),
        (
            "O seguro cobre este tipo de avaria?",
            "Does insurance cover this type of damage?",
            "ooh seh-GOO-roo KOH-bree ESH-teh TEE-poo deh ah-vah-REE-uh?",
            "o · se · gu · ro · co · bre · es · te · ti · po · de · a · va · ri · a",
            "Confirm details with your insurer—phrase is practice only.",
            "Insurance with English in-SHOOR-ance.",
        ),
        (
            "Queria falar com o chefe de oficina",
            "I would like to speak with the workshop manager",
            "kreh-REE-uh fah-LAR kong oo SHEH-fee deh oh-fee-SEE-nuh",
            "que · ri · a · fa · lar · com · o · che · fe · de · o · fi · ci · na",
            "Oficina for garage; polite request.",
            "Workshop with English WORK-shop.",
        ),
        (
            "Obrigado, fico à espera do orçamento",
            "Thanks, I will wait for the quote",
            "oh-bree-GAH-doo, FEE-koo ah eesh-PEH-ruh doo ohr-sah-MEN-too",
            "o · bri · ga · do · fi · co · à · es · pe · ra · do · or · ça · men · to",
            "Polite close; measured patience.",
            "Complaining loudly while waiting.",
        ),
    ],
    ("B2", 1): [
        (
            "Podemos alinhar expectativas para esta sprint?",
            "Can we align expectations for this sprint?",
            "poh-DEH-moosh ah-lee-NYAR eks-pek-tah-TEE-vash PAH-ruh ESH-tah sprint?",
            "po · de · mos · a · lin · har · ex · pec · ta · ti · vas · pa · ra · es · ta",
            "Borrowed sprint stays light; keep European PT rhythm.",
            "Corporate English intonation on every word.",
        ),
        (
            "Vou documentar isto no Confluence",
            "I will document this in Confluence",
            "voh do-koo-men-TAR EESH-too noo KON-floo-ens",
            "vou · do · cu · men · tar · is · to · no · Con · flu · ence",
            "Product names can stay close to English; PT vowels around them.",
            "Over-anglicizing every syllable.",
        ),
        (
            "Preciso de feedback até sexta",
            "I need feedback by Friday",
            "preh-SEE-zoo deh FEED-bak ah-TEH SAYSH-tuh",
            "pre · ci · so · de · feed · back · a · té · sex · ta",
            "Loanword feedback is common; sexta clear.",
            "Stressing FEEDBACK like a slogan.",
        ),
        (
            "Estou com alguma dúvida sobre o roadmap",
            "I have a question about the roadmap",
            "es-TONG kong al-GOO-muh DOO-vee-dah SOH-broo hoo ROHD-map",
            "es · tou · com · al · gu · ma · dú · vi · da · so · bre · o · road · map",
            "Soft sobre; keep professional calm.",
            "Heavy R in roadmap.",
        ),
        (
            "Podemos falar depois do stand-up?",
            "Can we talk after the stand-up?",
            "poh-DEH-moosh fah-LAR deh-Poysh doo stand-up?",
            "po · de · mos · fa · lar · de · pois · do · stand · up",
            "Natural code-switch; maintain Portuguese melody.",
            "Turning it into a command.",
        ),
        (
            "Consigo entregar isto até ao final do dia",
            "I can deliver this by end of day",
            "kon-SEE-goo en-treh-GAR EESH-too AH-teh ow fee-NAHL doo DEE-uh",
            "con · si · go · en · tre · gar · is · to · a · té · ao · fi · nal · do · dia",
            "Final do dia is common; keep vowels clear.",
            "End of day with English END-uv-day.",
        ),
        (
            "Há um conflito de prioridades",
            "There is a conflict of priorities",
            "ah oong kon-FLEE-too deh pree-oh-ree-DAH-desh",
            "há · um · con · fli · to · de · pri · o · ri · da · des",
            "Plural des crisp; calm framing.",
            "Conflict with English CON-flict.",
        ),
        (
            "Proponho adiarmos a reunião para amanhã",
            "I propose we postpone the meeting until tomorrow",
            "proo-POH-nyoo ah-dee-AR-moosh ah ray-oo-nee-OWN PAH-ruh ah-mahn-YAHNG",
            "pro · po · nho · a · di · ar · mos · a · re · u · ni · ão · pa · ra · a · man · hã",
            "Nasal ão in reunião; polite proposal tone.",
            "Propose sounding like a decree.",
        ),
        (
            "Fico disponível para uma chamada rápida",
            "I am available for a quick call",
            "FEE-koo dees-poh-NEE-vel PAH-ruh OO-muh shah-MAH-duh RAH-pee-dah",
            "fi · co · dis · po · ni · vel · pa · ra · u · ma · cha · ma · da · rá · pi · da",
            "Chamada with sh-like ch in many accents.",
            "Quick call with English QUICK CALL stress.",
        ),
        (
            "Obrigado pelo contexto",
            "Thanks for the context",
            "oh-bree-GAH-doo PEH-loo kon-TEHSH-too",
            "o · bri · ga · do · pe · lo · con · tes · to",
            "Warm close after a meeting block.",
            "Leaving a thread without acknowledging others.",
        ),
    ],
    ("B2", 2): [
        (
            "Tenho o NIF e o NISS impressos",
            "I have my NIF and NISS printed",
            "TEN-yoo ooh neef ee ooh neesh im-PREH-soosh",
            "ten · ho · o · NIF · e · o · NISS · im · pre · sos",
            "Acronyms spelled softly; plural sos.",
            "Yelling acronyms.",
        ),
        (
            "A minha marcação é às onze",
            "My appointment is at eleven",
            "ah MEE-nyah mar-kah-SOWN eh ash OHNZ",
            "a · mi · nha · mar · ca · ção · é · às · on · ze",
            "Nasal ção; às short.",
            "Eleven with English e-LEV-en.",
        ),
        (
            "Trago comprovativo de morada",
            "I brought proof of address",
            "TRAH-goo kom-proo-vah-TEE-voo deh moh-RAH-duh",
            "tra · go · com · pro · va · ti · vo · de · mo · ra · da",
            "Even rhythm; official but friendly.",
            "Swallowing comprovativo.",
        ),
        (
            "Ainda falta algum documento?",
            "Is any document still missing?",
            "ah-EEN-dah FAL-tah al-GOONG do-koo-MEN-too?",
            "a · in · da · fal · ta · al · gum · do · cu · men · to",
            "Rising intonation; polite check-in.",
            "Blunt what is missing.",
        ),
        (
            "Obrigado pela vossa ajuda",
            "Thank you for your help",
            "oh-bree-GAH-doo PEH-luh VOH-sah ah-ZHOO-dah",
            "o · bri · ga · do · pe · la · vos · sa · a · ju · da",
            "Vossa formal plural; warm close.",
            "Too informal for a counter context.",
        ),
        (
            "Confirmo que compreendi os próximos passos",
            "I confirm I understood the next steps",
            "kon-feer-MOO keh kom-pree-EN-dee oosh PROK-see-moosh PAH-soosh",
            "con · fir · mo · que · com · pre · en · di · os · pró · xi · mos · pas · sos",
            "Plural passos crisp; professional tone.",
            "Monotone confirmation sounding sarcastic.",
        ),
        (
            "Podemos solicitar esclarecimentos por escrito?",
            "Can we request clarifications in writing?",
            "poh-DEH-moosh so-lee-see-TAR eesh-klah-reh-see-MEN-toosh poor eesh-KREE-too?",
            "po · de · mos · so · li · ci · tar · es · cla · re · ci · men · tos · por · es · cri · to",
            "Long word—slow down; polite question.",
            "Rushing the whole sentence.",
        ),
        (
            "Há uma fila virtual para este serviço?",
            "Is there a virtual queue for this service?",
            "ah OO-muh FEE-luh veer-too-AHL PAH-ruh ESH-teh sehr-VEE-soo?",
            "há · u · ma · fi · la · vir · tu · al · pa · ra · es · te · ser · vi · ço",
            "Ç like s; useful in modern offices.",
            "Virtual with English VER-choo-ul.",
        ),
        (
            "Queria confirmar se o processo está concluído",
            "I would like to confirm whether the process is completed",
            "kreh-REE-uh kon-feer-MAR seh oo pro-SEH-soo es-TAH kon-kloo-EE-doo",
            "que · ri · a · con · fir · mar · se · o · pro · ce · so · es · tá · con · cluí · do",
            "Nasal está; keep calm official tone.",
            "Process with English PRAH-sess.",
        ),
        (
            "Obrigado pela vossa paciência",
            "Thank you for your patience",
            "oh-bree-GAH-doo PEH-luh VOH-sah pah-see-EN-syuh",
            "o · bri · ga · do · pe · la · vos · sa · pa · ci · en · cia",
            "Warm close after long waits.",
            "Complaining loudly at the end.",
        ),
    ],
    ("B2", 3): [
        (
            "Compreendo o teu ponto, mas…",
            "I understand your point, but…",
            "kom-preh-EN-doo ooh tew POHN-too, mash...",
            "com · pre · en · do · o · teu · pon · to · mas",
            "Soft entry; mas leads calmly into contrast.",
            "Starting with NO energy.",
        ),
        (
            "Eu veria isto de outra forma",
            "I would see it another way",
            "eh-oo veh-REE-uh EESH-too deh OH-trah FOR-muh",
            "eu · ve · ri · a · is · to · de · ou · tra · for · ma",
            "Polite conditional; measured pace.",
            "Over-apologizing before every word.",
        ),
        (
            "Não estou totalmente de acordo",
            "I do not fully agree",
            "nowng es-TOH toh-tal-MEN-teh deh ah-KOR-doo",
            "não · es · tou · to · tal · men · te · de · a · cor · do",
            "Nasal não; avoid sounding sharp.",
            "Monotone that sounds rude.",
        ),
        (
            "Há nuances que vale a pena notar",
            "There are nuances worth noting",
            "ah noo-AHN-sash keh VAH-lee ah PEH-nah noo-TAR",
            "há · nu · an · cas · que · va · le · a · pe · na · no · tar",
            "Borrowed nuances can stay French-lite; keep PT vowels.",
            "Rushing the closing.",
        ),
        (
            "Podemos explorar uma alternativa?",
            "Can we explore an alternative?",
            "poh-DEH-moosh eks-ploh-rah-ROO-mah al-tehr-nah-TEE-vuh?",
            "po · de · mos · ex · plo · rar · u · ma · al · ter · na · ti · va",
            "Polite question; open vowels on alternativa.",
            "Closed, confrontational tone.",
        ),
        (
            "Prefiro ser transparente contigo",
            "I prefer to be transparent with you",
            "preh-FEE-roo sehr trahns-pah-REHN-teh kon-TEE-goo",
            "pre · fi · ro · ser · trans · pa · ren · te · con · ti · go",
            "Transparente with European vowels; calm tone.",
            "Transparent with English trans-PAIR-ent.",
        ),
        (
            "Não quero soar inflexível",
            "I do not want to sound inflexible",
            "nowng KEH-roo soh-AR een-fleh-KSEE-vel",
            "não · que · ro · so · ar · in · fle · xí · vel",
            "Nasal não; self-aware tone helps rapport.",
            "Sounds like a lecture.",
        ),
        (
            "Podemos encontrar um meio-termo?",
            "Can we find a middle ground?",
            "poh-DEH-moosh en-kon-TRAHR oong MAY-oo-TEHR-moo?",
            "po · de · mos · en · con · trar · um · mei · o · ter · mo",
            "Meio-termo flows; polite question.",
            "Middle ground explained in English only.",
        ),
        (
            "Agradeço a franqueza",
            "I appreciate the frankness",
            "ah-grah-DEH-soo ah frahn-KAY-zuh",
            "a · gra · de · ço · a · fran · que · za",
            "Franqueza with clear vowels; respectful.",
            "Frankness sounding sarcastic.",
        ),
        (
            "Ficamos então com este plano",
            "We will go with this plan then",
            "fee-KAH-moosh en-TOWNG kong ESH-teh PLAH-noo",
            "fi · ca · mos · en · tão · com · es · te · pla · no",
            "Nasal então; collaborative close.",
            "Imposing this plan is final.",
        ),
    ],
    ("B2", 4): [
        (
            "Desculpe o incómodo do barulho",
            "Sorry for the noise inconvenience",
            "desh-KOOL-poo o een-KOH-moo-doo doo bah-ROOL-yoo",
            "des · cul · pe · o · in · có · mo · do · do · ba · ru · lho",
            "Polite opener; barulho common complaint word.",
            "Starting with accusation instead of apology.",
        ),
        (
            "Vamos tentar resolver isto em bom tom",
            "Let us try to resolve this in good faith",
            "VAH-moosh ten-TAR heh-zol-VEHR EESH-too ayng bohng tohng",
            "va · mos · ten · tar · re · sol · ver · is · to · em · bom · tom",
            "Em bom tom is idiomatic; keep calm.",
            "Good faith translated too literally and sounding odd.",
        ),
        (
            "O horário de silêncio começa à meia-noite",
            "The quiet hours start at midnight",
            "ooh oh-ree-AH-ree-oo deh see-LENG-see-oo koo-MEH-sah ah MAY-uh NOY-tuh",
            "o · ho · rá · ri · o · de · si · lên · ci · o · co · me · ça · à · mei · a · noi · te",
            "Meia-noite with clear vowels; building rules vary.",
            "Midnight with English MID-night stress.",
        ),
        (
            "Podemos combinar um horário que funcione para todos?",
            "Can we agree on a schedule that works for everyone?",
            "poh-DEH-moosh kom-bee-NAR oong oh-ree-AH-ree-oo keh foon-see-OH-neh PAH-ruh TOH-doosh?",
            "po · de · mos · com · bi · nar · um · ho · rá · ri · o · que · fun · ci · o · ne · pa · ra · to · dos",
            "Plural todos; polite collaborative question.",
            "Schedule with English SKED-jool.",
        ),
        (
            "Agradeço a compreensão dos vizinhos",
            "I appreciate the neighbors understanding",
            "ah-grah-DEH-soo ah kom-pree-en-SOWN doosh vee-ZEE-nyoosh",
            "a · gra · de · ço · a · com · pre · en · são · dos · vi · zi · nhos",
            "Vizinhos with nh; plural nhos crisp.",
            "Neighbors with English NAY-bors.",
        ),
        (
            "Não foi a minha intenção incomodar",
            "It was not my intention to disturb",
            "nowng foy ah MEE-nyah een-ten-SOWN een-koh-moh-DAR",
            "não · foi · a · mi · nha · in · ten · ção · in · co · mo · dar",
            "Nasal intenção; polite repair attempt.",
            "Defensive it is not my fault opener.",
        ),
        (
            "Posso ajudar com uma solução prática?",
            "Can I help with a practical solution?",
            "POH-soo ah-zhoo-DAR kong OO-muh so-loo-SOWN PRAH-tee-kuh?",
            "pos · so · a · ju · dar · com · u · ma · so · lu · ção · prá · ti · ca",
            "Nasal ção; collaborative tone.",
            "Help with English HELP shouted.",
        ),
        (
            "Fico grato pela colaboração",
            "I am grateful for the cooperation",
            "FEE-koo GRAH-too PEH-luh koo-lah-boh-rah-SOWN",
            "fi · co · gra · to · pe · la · co · la · bo · ra · ção",
            "Nasal ção; warm formal tone.",
            "Cooperation with English co-OP-er-ation.",
        ),
        (
            "Podemos marcar um café rápido no prédio?",
            "Can we schedule a quick coffee in the building?",
            "poh-DEH-moosh mar-KAR oong kah-FEH RAH-pee-doo noo PRAY-dee-oo?",
            "po · de · mos · mar · car · um · ca · fé · rá · pi · do · no · pré · di · o",
            "Prédio with European vowels; informal bridge-building.",
            "Coffee meeting sounding like interrogation.",
        ),
        (
            "Obrigado pela conversa",
            "Thanks for the conversation",
            "oh-bree-GAH-doo PEH-luh kon-VEHR-suh",
            "o · bri · ga · do · pe · la · con · ver · sa",
            "Warm close after neighbor talk.",
            "Walking away mid-sentence.",
        ),
    ],
    ("B2", 5): [
        (
            "A minha filha está na creche",
            "My daughter is at daycare",
            "ah MEE-nyah FEE-lyah es-TAH nah KREH-shuh",
            "a · mi · nha · fi · lha · es · ta · na · cre · che",
            "Creche with sh-like ch in many accents.",
            "Daycare with English DAY-care.",
        ),
        (
            "O meu filho frequenta a escola pública",
            "My son attends public school",
            "ooh may-oo FEEL-yoo freh-KWEN-tah ah ehs-KOH-lah POO-blee-kuh",
            "o · meu · fi · lho · fre · quen · ta · a · es · co · la · pú · bli · ca",
            "Pública with clear vowels; neutral phrasing.",
            "Public with English PUB-lic stress.",
        ),
        (
            "Há reunião de pais esta semana?",
            "Is there a parents meeting this week?",
            "ah ray-oo-nee-OWN deh pah-ee ESH-teh seh-NAH-nuh?",
            "há · re · u · ni · ão · de · pa · is · es · te · se · ma · na",
            "Nasal ão; plural pais crisp.",
            "Parents meeting with English PAIR-ents.",
        ),
        (
            "Queria combinar um horário para buscar a criança",
            "I would like to arrange a time to pick up the child",
            "kreh-REE-uh kom-bee-NAR oong oh-ree-AH-ree-oo PAH-ruh boosh-KAR ah kree-AHN-suh",
            "que · ri · a · com · bi · nar · um · ho · rá · ri · o · pa · ra · bus · car · a · cri · an · ça",
            "Criança with nasal ça; polite planning tone.",
            "Pick up with English PICK-up command tone.",
        ),
        (
            "O transporte escolar passa aqui perto?",
            "Does the school bus pass near here?",
            "ooh trahns-POR-teh ehs-koh-LAR PAH-suh ah-KEE PEHR-too?",
            "o · trans · por · te · es · co · lar · pas · sa · a · qui · per · to",
            "Escolar adjective agreement; clear question.",
            "School bus with English SKOOL bus.",
        ),
        (
            "Preciso de um contacto da professora",
            "I need a contact for the teacher",
            "preh-SEE-zoo deh oong kon-TAK-too dah proo-feh-SOH-ruh",
            "pre · ci · so · de · um · con · tac · to · da · pro · fe · so · ra",
            "Contacto spelling in Portugal; polite request.",
            "Contact with English CON-tact.",
        ),
        (
            "Há lista de materiais para o ano letivo?",
            "Is there a materials list for the school year?",
            "ah LEESH-tah deh mah-teh-ree-ah-eesh PAH-ruh ooh AH-noo leh-TEE-voo?",
            "há · lis · ta · de · ma · te · ri · ais · pa · ra · o · a · no · le · ti · vo",
            "Letivo school-year term; confirm with school.",
            "Materials with English mah-TEER-ee-uls.",
        ),
        (
            "Podemos partilhar o calendário escolar?",
            "Can we share the school calendar?",
            "poh-DEH-moosh par-tee-LHAR oo kah-len-DAH-ree-oo ehs-koh-LAR?",
            "po · de · mos · par · ti · lhar · o · ca · len · dá · ri · o · es · co · lar",
            "Partilhar is share in Portugal; keep rhythm.",
            "Share with English SHARE emphasis.",
        ),
        (
            "Obrigado pela informação",
            "Thanks for the information",
            "oh-bree-GAH-doo PEH-luh een-for-mah-SOWN",
            "o · bri · ga · do · pe · la · in · for · ma · ção",
            "Nasal ção; polite close after office talk.",
            "Information with English in-for-MAY-shun.",
        ),
        (
            "Boa tarde, até logo",
            "Good afternoon, see you later",
            "BOH-uh TAR-deh, AH-teh LOH-goo",
            "boa · tar · de · a · té · lo · go",
            "Short friendly close at the school gate.",
            "See you later with American SEE-ya.",
        ),
    ],
}
